version: '3'

services:
  database:
    image: mariadb
    restart: always
    volumes:
      - db_data:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: root
      MYSQL_DATABASE: wordpress
  wordpress:
    build: ./wordpress
    image: dataramdevelopment/wordpress
    depends_on:
      - database
    ports:
      - "8000:80"
    restart: always
    volumes:
      - ./wordpress:/var/www/html/
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
     - 8081:80
    depends_on: 
      - database
    expose:
      - 8000
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: password 
  frontend:
    build: ./mentor-listing-src
    depends_on:
      - wordpress
    command: npm run serve
    volumes:
      - ./mentor-listing-src:/app/ 
    ports:
      - "3000:3000"
    restart: always
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
volumes:
  db_data:
  wordpress_data: