version: '3'

services:
  database:
    image: mariadb
    restart: always
    volumes:
      - tech_incubator_db_data:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: root
      MYSQL_DATABASE: wordpress
    networks:
      - nginxproxy_default
  wordpress:
    build: ./wordpress
    image: dataramdevelopment/wordpress
    depends_on:
      - database
    ports:
      - "9000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    networks:
      - nginxproxy_default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
     - 8081:80
    depends_on: 
      - database
    expose:
      - 8000
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: password
    networks:
      - nginxproxy_default
  nginx:
    image: nginx:latest
    ports:
      - '80'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx
      - ./wordpress:/var/www/html
    restart: always
    networks:
      - nginxproxy_default
  nginx-proxy:
    container_name: nginx-proxy
    build: ./proxy
    image: nginx-proxy:0.0.2
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - nginx
    volumes:
      - "./etc/letsencrypt/:/etc/letsencrypt/"
      - "./etc/ssl/:/etc/ssl/"
    command: bash -c "startup.sh"
    restart: always
volumes:
  tech_incubator_db_data:
  wordpress_data:
networks:
  nginxproxy_default:
    external: true